
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 22 12:10:34 CDT 2022
//----------------------------------------------------

package fes.aragon.compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 4;
  public static final int MENOR = 12;
  public static final int PUNTOYCOMA = 2;
  public static final int ENTRE = 6;
  public static final int RPAREN = 9;
  public static final int MENORIGUAL = 13;
  public static final int UMENOS = 7;
  public static final int LPAREN = 8;
  public static final int ID = 16;
  public static final int POR = 5;
  public static final int MAYOR = 14;
  public static final int EOF = 0;
  public static final int MAYORIGUAL = 15;
  public static final int NUMERO = 17;
  public static final int PRINT = 10;
  public static final int error = 1;
  public static final int ASIG = 11;
  public static final int MAS = 3;
}

