
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 16 11:23:16 CDT 2022
//----------------------------------------------------

package fes.aragon.compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IZQ = 10;
  public static final int ABAJO = 9;
  public static final int VER = 4;
  public static final int DER = 11;
  public static final int ARRIBA = 8;
  public static final int EOF = 0;
  public static final int NUMERO = 14;
  public static final int error = 1;
  public static final int COLOCA = 6;
  public static final int PARC = 13;
  public static final int MOVER = 7;
  public static final int PUNTOYCOMA = 2;
  public static final int REPETIR = 3;
  public static final int PARA = 12;
  public static final int FRUTA = 5;
}

